run:
  tests: false
  deadline: 5m

linters-settings:
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - interfacer # deprecated
    - scopelint # deprecated
    - maligned # deprecated
    - golint # deprecated
    - cyclop
    - exhaustive
    - exhaustivestruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - goerr113
    - gomnd
    - nestif
    - nlreturn
    - tagliatelle
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
  exclude:
    - 'G103: Use of unsafe calls should be audited'
  exclude-rules:
  - path: (schema|protocol)\.go
    linters:
      - gosec