run:
  tests: false
  timeout: 5m
linters:
  enable-all: true
  disable:
    - cyclop
    - errorlint
    - exhaustive
    - exhaustivestruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - goerr113
    - golint
    - gomnd
    - interfacer
    - maligned
    - nestif
    - noctx
    - nlreturn
    - scopelint
    - tagliatelle
    - testpackage
    - wrapcheck
    - wsl
issues:
  exclude-rules:
  - path: (schema|protocol)\.go
    linters:
      - gosec